# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrqp56QXy-rRJtCXU_zSc6EPd1rgBg9l
"""

!pip install langchain langchain-community gradio python-dotenv
!pip install groq

from ui.gradio_ui import interface
from dotenv import load_dotenv

from dotenv import load_dotenv
load_dotenv()

if __name__ == "__main__":
    interface.launch()